### ISSUE TITLE
Quickly get white candles

### ISSUE THREAD

**Issue by IctLang** [XeTrinityz/ThatSkyApp#1]
Hello authors, thank you for contributing to the community. I have some suggestions and questions to share.
**About the menu**
1. Add Chinese support and even AI translation. The text in the menu should all appear in the language profile, I translated 100% of the profile, but only 80% of the menu content.
2. Font files can read fonts that come with Windows. Or provide a save function so you don't need to set it every time.

**About the game**
1. The frame rate of the game drops intermittently, and no features are turned on (R9 5900HX RTX3060 notebook).
2. Add the candle suction in-place function, stand at home, and the candle absorbs on its own.
3. Sacrifice quickly to get the Red Candle
4. Quickly unlock seasonal ancestors(ideas from other cheat programs)

**Comment by XeTrinityz** [comment]
If you join the Discord, TSM has two Chinese translation files available. As for some items not being translated, this may be due to technical reasons. However, you can provide a list of missing translatable items as it may have been an oversight. I am unsure what you mean by "Sacrifice quickly to get the Red Candle" and "Quickly unlock seasonal ancestors(ideas from other cheat programs)". 

In terms of frame rate issues, you should try reinstalling your graphics drivers with DDU and reinstall VC Redist.

**Comment by IctLang** [comment]
think

**Comment by IctLang** [comment]
Maybe I can give you a sample

**Comment by IctLang** [comment]
如何联系你呢
